# Generated by Django 3.0 on 2019-12-02 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SambaGlobal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SambaShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('recycle', models.BooleanField()),
                ('btrfs', models.BooleanField()),
                ('enabled', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SambaOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samba.SambaShare')),
            ],
        ),
    ]
